/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#396664",
        "primary-fixed": "#bcebe9",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f4f3",
        "surface-container": "#edeeed",
        "on-primary-fixed-variant": "#204e4d",
        "outline-variant": "#c0c8c7",
        "error-container": "#ffdad6",
        "surface-container-high": "#e7e8e7",
        "on-tertiary-container": "#c7917a",
        "surface-variant": "#e1e3e2",
        "surface-dim": "#d9dad9",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00201f",
        "on-error": "#ffffff",
        outline: "#707978",
        "on-tertiary-fixed": "#311305",
        surface: "#f9f9f8",
        primary: "#002423",
        "secondary-fixed-dim": "#b8cac9",
        "primary-fixed-dim": "#a1cfcd",
        "inverse-primary": "#a1cfcd",
        "primary-container": "#073b3a",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#f4b9a1",
        "on-secondary-container": "#556665",
        "tertiary-container": "#502b1a",
        "surface-container-highest": "#e1e3e2",
        "inverse-surface": "#2e3131",
        "secondary-fixed": "#d4e6e5",
        secondary: "#516261",
        tertiary: "#361607",
        "on-secondary-fixed": "#0e1e1e",
        "tertiary-fixed": "#ffdbcd",
        "surface-bright": "#f9f9f8",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#394a49",
        "on-tertiary-fixed-variant": "#653d2a",
        "on-background": "#191c1c",
        "secondary-container": "#d1e3e2",
        "on-primary-container": "#78a5a3",
        "on-surface": "#191c1c",
        "on-surface-variant": "#404848",
        "inverse-on-surface": "#f0f1f0",
        background: "#f9f9f8",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        poppins: ["Poppins", "Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      boxShadow: {
        editorial: "0 20px 40px rgba(0, 36, 35, 0.06)",
      },
    },
  },
  plugins: [],
};
